version: '3.8'

services:
  db:
    image: neo4j:5.8.0-enterprise
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_backup_enabled=true
      - NEO4J_server_backup_listen__address=0.0.0.0:6362
    ports:
      - "7474:7474" # Open Neo4j browser
      - "7687:7687" # Bolt port

  db-backup:
    build:
      context: .
      dockerfile: Dockerfile-backups
    # Ensures the cron service keeps running
    tty: true
    volumes:
      - ./backups:/var/lib/neo4j/backups
